services:
  nginx_server:
    image: nginx:1.27
    depends_on:
      - myapp
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/nginx:/etc/nginx
      - ./logs/nginx:/var/log/nginx
      - ./public:/usr/share/nginx/html
      - /etc/letsencrypt/live:/etc/nginx/ssl/live
  myapp:
    build:
      context: ./app