services:
  nginx_server:
    image: nginx:1.27
    depends_on:
      - myapp
    ports:
      - 5050:80
    volumes:
      - ./config/nginx:/etc/nginx
      - ./logs/nginx:/var/log/nginx
      - ./public:/usr/share/nginx/html
  myapp:
    build:
      context: ./app